title: 'Develop an ASP.NET Core app that consumes an API'
remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#  syntax_highlighter: rouge
