name: FruitWebApp Render
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - Allfiles/Labs/FruitWebApp-render/**

defaults:
  run:
    shell: pwsh

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Fruit zip
      run: | 
        cd ./Allfiles/Labs/FruitWebApp-render
        zip -r -q ../../Downloads/FruitWebApp-render.zip * .vscode/*
    - name: Commit and push
      uses: Endbug/add-and-commit@v7
      with:
        add: '["Allfiles/Downloads/FruitWebApp-render.zip"]'
        message: 'Updating Zip for render source files'
        push: true
